### ISSUE TITLE
Will there be any minor upgrade to support the latest version of flarum?

### ISSUE THREAD

**Issue by Mr-Sheep** [clarkwinkelmann/flarum-ext-see-past-first-post#9]
First of all, thank you for developing such an awesome extension for flarum.
I got this error message say that package does not match your minimum-stability. Will there be any upgrades on that?

```
> composer require clarkwinkelmann/flarum-ext-see-past-first-post --with-all-dependencies
Using version ^1.1 for clarkwinkelmann/flarum-ext-see-past-first-post
./composer.json has been updated
Running composer update clarkwinkelmann/flarum-ext-see-past-first-post --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires clarkwinkelmann/flarum-ext-see-past-first-post ^1.1 -> satisfiable by clarkwinkelmann/flarum-ext-see-past-first-post[1.1.0].
    - clarkwinkelmann/flarum-ext-see-past-first-post 1.1.0 requires flarum/core >=0.1.0-beta.15 <0.1.0-beta.16 -> found flarum/core[v0.1.0-beta.15] but it does not match your minimum-stability.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.

```

**Comment by Mr-Sheep** [comment]
I noticed that there are [merge requests](https://github.com/clarkwinkelmann/flarum-ext-see-past-first-post/pull/8) from dependabot. Can you kindly merge them into the master branch?

**Comment by clarkwinkelmann** [comment]
The error is because the package isn't compatible with Flarum 1.0. I don't think the code works on 1.0 without changes, so just changing the Flarum core requirement won't solve the issue. I am not planning to update this extension without a sponsorship (at least 2 hours of work sponsored across one or multiple extensions). This extension might be 15-30min of work to make compatible.

I never merge dependabot PRs, I manually update JS depdendencies through yarn. But this is unimportant because those PRs generally only update libraries that are used as part of webpack and not as part of the output code itself. And the PRs don't recompile the dist files anyway, so it wouldn't even solve the rarer client-side security issues. If an update is sponsored, I'll update all JS deps to the latest version before testing.

**Comment by Mr-Sheep** [comment]
> I am not planning to update this extension without a sponsorship (at least 2 hours of work sponsored across one or multiple extensions). This extension might be 15-30min of work to make compatible.

If I am understanding correctly, if I only want you to help upgrading this extension, roughly about 30 minutes work, I still need to sponsor at least 2 hours of work?
Correct me if I'm wrong.

**Comment by clarkwinkelmann** [comment]
This page describes how I usually do sponsored work https://clarkwinkelmann.com/flarum#extension-development

I sometimes makes exceptions, but for the most efficient use of my time I require at least 2 hours of work, otherwise I spend more time setting up instead of actually working. When it's just updates and not any new feature the ideal solution is to sponsor multiple extensions, that way I can do all of them at the same time. But since there aren't many extensions left to update now it's of course a bit tricky to have 2 hours of work just making updates.

I don't have a lot of time available in the immediate future so the more work is sponsored at once, the easier it is for me to dedicate a day to just do that instead of having to find a bit of time between 2 completely different things.

**Comment by clarkwinkelmann** [comment]
Version 1.2.0 released with support for Flarum stable.
